[package]
name = "ultimate_tex"
version = "0.2.1"
edition = "2021"

[dependencies]
nutexb = { git = "https://github.com/jam1garner/nutexb", features = ["ddsfile"] }
bntx = { git = "https://github.com/ScanMountGoat/bntx", rev = "73fe278" }
image_dds = { git = "https://github.com/ScanMountGoat/image_dds", rev = "7e2cc26" }
image = "0.24.5"
ddsfile = "0.5.1"
strum = { version = "0.24", features = ["derive"] }