[package]
name = "ultimate_tex"
version = "0.2.3"
edition = "2021"

[dependencies]
nutexb = { git = "https://github.com/jam1garner/nutexb", features = ["ddsfile"] }
bntx = { git = "https://github.com/azel-s/bntx" }
image_dds = { git = "https://github.com/ScanMountGoat/image_dds", rev = "6debc74" }
strum = { version = "0.24", features = ["derive"] }