[package]
name = "ultimate_tex_app"
version = "0.1.0"
edition = "2021"

[dependencies]
ultimate_tex = { path = "../ultimate_tex" }
eframe = "0.20.1"
egui_extras = { version = "0.20.0", features = ["image"] }
image = "0.24.5"
image_dds = { git = "https://github.com/ScanMountGoat/image_dds" }
strum = { version = "0.24", features = ["derive"] }
rfd = "0.11.0"
globwalk = "0.8.1"
rayon = "1.6.1"
open = "3"