[package]
name = "ultimate_tex_cli"
version = "0.3.0"
edition = "2021"

[dependencies]
ultimate_tex_lib = { path = "../ultimate_tex_lib" }
image_dds = "0.7.0"
clap = { version = "4.1.1", features = ["derive"] }
anyhow = "1.0"