name: Compile Release

on: 
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  # build-windows:
  #   runs-on: windows-latest
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: setup node
  #     uses: actions/setup-node@v3
  #     with:
  #       node-version: 16
  #   - name: Install Tauri
  #     uses: baptiste0928/cargo-install@v2
  #     with:
  #       crate: tauri-cli
  #       version: "1.4"
  #       locked: false
  #       args: --debug
  #   - name: Build
  #     run: |
  #       cd ultimate_tex_tauri
  #       npm install
  #       cargo tauri build --bundles none
  #   - name: Create Zip
  #     run: Compress-Archive -path target/release/ultimate_tex.exe -destinationPath ultimate_tex_win_x64.zip 
  #   - name: Upload Zip
  #     uses: actions/upload-artifact@v3
  #     with:
  #       name: ultimate_tex_win_x64
  #       path: ultimate_tex_win_x64.zip

  # build-macos:
  #   runs-on: macos-latest
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: setup node
  #     uses: actions/setup-node@v3
  #     with:
  #       node-version: 16
  #   - name: Install Rust Toolchain
  #     uses: actions-rs/toolchain@v1
  #     with:
  #       toolchain: stable
  #       target: aarch64-apple-darwin
  #   - name: Install Tauri
  #     uses: baptiste0928/cargo-install@v2
  #     with:
  #       crate: tauri-cli
  #       version: "1.4"
  #       locked: false
  #       args: --debug
  #   - name: Install Packages
  #     run: |
  #       cd ultimate_tex_tauri
  #       npm install
  #       cd ..
  #   - name: Build
  #     run: |
  #       cargo tauri build --bundles app --target x86_64-apple-darwin
  #       cargo tauri build --bundles app --target aarch64-apple-darwin
  #   - name: Sign Binaries
  #     run: |
  #       codesign -s - target/x86_64-apple-darwin/release/bundle/macos/ultimate_tex.app
  #       codesign -s - target/aarch64-apple-darwin/release/bundle/macos/ultimate_tex.app
  #   - name: Create Zips
  #     run: |
  #       cp -r target/x86_64-apple-darwin/release/bundle/macos/ultimate_tex.app ultimate_tex.app
  #       zip -r ultimate_tex_macos_intel.zip ultimate_tex.app
  #       cp -r target/aarch64-apple-darwin/release/bundle/macos/ultimate_tex.app ultimate_tex.app
  #       zip -r ultimate_tex_macos_apple_silicon.zip ultimate_tex.app
  #   - name: Upload Zip Intel
  #     uses: actions/upload-artifact@v3
  #     with:
  #       name: ultimate_tex_macos_intel
  #       path: ultimate_tex_macos_intel.zip
  #   - name: Upload Zip Apple Silicon
  #     uses: actions/upload-artifact@v3
  #     with:
  #       name: ultimate_tex_macos_apple_silicon
  #       path: ultimate_tex_macos_apple_silicon.zip

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install Ubuntu Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libssl-dev libgtk-3-dev libsoup2.4-dev webkit2gtk-4.0 javascriptcoregtk-4.0
    - name: Build
      run: |
        cd ultimate_tex_tauri
        npm install
        mkdir build
        cargo build --release
    - name: Create Zip
      run: |
        cp target/release/ultimate_tex_tauri ultimate_tex
        zip ultimate_tex_linux_x64.zip ultimate_tex
    - name: Upload Zip
      uses: actions/upload-artifact@v3
      with:
        name: ultimate_tex_linux_x64
        path: ultimate_tex_linux_x64.zip
