name: Compile Release

on: 
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Install GTK3
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get update && sudo apt-get install libgtk-3-dev
    - name: Build
      run: cargo build
