name: Compile Release

on: 
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install Tauri
      uses: baptiste0928/cargo-install@v2
      with:
        crate: tauri-cli
        version: "1.4"
    - name: Build
      run: |
        cd ultimate_tex_tauri
        npm install
        cargo tauri build --bundles none
    - name: Upload Zip
      uses: actions/upload-artifact@v3
      with:
        name: Release
        path: target/release/ultimate_tex.exe
